version: '3.8'

services:
  client:
    build:
      context: ../cloud-doc-mgmt-client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development

  server:
    build:
      context: ../cloud-doc-mgmt-server
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    environment:
      - NODE_ENV=development
